name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Reach VM and start Docker container
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            set -e
            echo "Stopping old container if it exists..."
            sudo docker stop payroll_container || true
            sudo docker rm payroll_container || true
            
            echo "Pulling latest commit"
            git switch main
            git pull origin main
            
            echo "Building image..."
            sudo docker build -t payroll:latest .
            cd payroll/Staffwizard_payroll
            sudo docker build -t payroll:latest .
            sudo docker run -d \
            --name payroll_container \
            -p 0.0.0.0:5001:5001 \
            --restart unless-stopped \
            payroll:latest
